{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-eudi-pid-issuer
  labels:
    app.kubernetes.io/name: eudi-pid-issuer
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default $.Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Release.Name }}-eudi-pid-issuer
                port:
                  number: {{ $.Values.service.port | default 8080 }}
          {{- end }}
    {{- end }}
{{- end }}
