apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-eudi-pid-issuer
  labels:
    app.kubernetes.io/name: eudi-pid-issuer
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  oauth-client-secret: {{ required "eudiPidIssuer.oauth.clientSecret is required" .Values.oauth.clientSecret | quote }}
  keycloak-password: {{ required "eudiPidIssuer.keycloak.password is required" .Values.keycloak.password | quote }}
  database-password: {{ required "eudiPidIssuer.database.password is required" .Values.database.password | quote }}
  statuslist-api-key: {{ required "eudiPidIssuer.statusList.apiKey is required" .Values.statusList.apiKey | quote }}
  keystore-password: {{ .Values.keystore.password | quote }}
  sdjwt-signing-password: {{ .Values.keystore.aliases.sdJwtSigningPassword | quote }}
  request-encryption-password: {{ .Values.keystore.aliases.requestEncryptionPassword | quote }}
  nonce-encryption-password: {{ .Values.keystore.aliases.nonceEncryptionPassword | quote }}
  access-certificate-password: {{ .Values.keystore.aliases.accessCertificatePassword | quote }}
{{- if not .Values.keystore.existingSecret }}
data:
  {{ .Values.keystore.secretKey }}: {{ .Files.Get "files/issuer-dev.jks" | b64enc }}
{{- end }}
